#pragma once
#include <math.h>
#include <string>
#include <iostream>
#include "TransformationMatrix.h"
#include "RotationMatrix.h"
#include "ScaleMatrix.h"
#include "TranslationMatrix.h"
#include "ShearXMatrix.h"
#include "ShearYMatrix.h"
#include "CompositeMatrix.h"